# Generated by Django 4.2.1 on 2023-05-21 07:04

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('mail_address', models.EmailField(blank=True, max_length=255, unique=True)),
                ('tel_num', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('birth_day', models.DateField(blank=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('inf_about', models.TextField(max_length=2550, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('mail', models.EmailField(blank=True, max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True)),
                ('tel_number', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('is_act', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=2550)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, max_length=25500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('auth_opinion', models.TextField(max_length=2550, null=True)),
                ('source', models.URLField(max_length=255, null=True)),
                ('d_created', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
                ('topic', models.ManyToManyField(to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.CharField(blank=True, max_length=255)),
                ('branch', models.TextField(blank=True, max_length=2550)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_d', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ManyToManyField(to='core.section')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
        ),
    ]
